export const fallbackSections = [
  {
    title: '自动结构化结果',
    description: '当前文档尚未抽取出完整章节时，系统展示默认结构。',
    items: [
      { title: '上传原文', body: '请在左侧上传 PDF、Word、TXT 或直接粘贴文本。', tag: '输入' },
      { title: '点击转换', body: '系统会先结构化整理，再生成可预览 HTML。', tag: '流程' },
    ],
  },
]

export const templateCatalog = [
  {
    id: 'template-02',
    renderer: 'magazine',
    name: '杂志版',
    title: '杂志封面周报',
    description: '保留封面感、目录感和专题导读，适合对外展示。',
    accent: '#C8382A',
    chip: 'MAGAZINE/02',
    focus: '适合品牌感较强的汇报场景和对外展示式周报。',
    bestFor: '专题汇报 / 品牌展示',
    departmentTags: ['comprehensive', 'international', 'research'],
    audienceTags: ['director', 'executive'],
    moduleBlueprint: ['封面主栏', '要览导读', '分栏工作', '数据图表', '签发信息'],
  },
  {
    id: 'template-03',
    renderer: 'ink',
    name: '国风版',
    title: '国风卷轴周报',
    description: '强调卷轴层次、章回节奏和仪式感封面。',
    accent: '#C41E3A',
    chip: 'INK/03',
    focus: '适合视觉辨识度较高的特色汇报。',
    bestFor: '特色汇报 / 对外展示',
    departmentTags: ['comprehensive', 'international', 'teaching'],
    audienceTags: ['director', 'executive'],
    moduleBlueprint: ['封面信息', '卷轴要览', '分类工作', '数据板块', '签发信息'],
  },
  {
    id: 'template-04',
    renderer: 'dashboard-plus',
    name: '仪表盘版',
    title: '控制台仪表盘周报',
    description: '强调执行追踪、进度看板和数据面板。',
    accent: '#00E5FF',
    chip: 'DASHBOARD/04',
    focus: '适合执行追踪、项目例会和运营复盘。',
    bestFor: '运营周会 / 项目推进',
    departmentTags: ['operations', 'research', 'comprehensive'],
    audienceTags: ['operations', 'executive'],
    moduleBlueprint: ['头部 KPI', '时间线要览', '分类看板', '数据可视化', '签发信息'],
  },
  {
    id: 'template-05',
    renderer: 'news',
    name: '新闻简报版',
    title: '新闻简报周报',
    description: '突出信息密度和栏目节奏，适合快速浏览。',
    accent: '#F5C842',
    chip: 'NEWS/05',
    focus: '适合信息密度高、亮点多的简报型周报。',
    bestFor: '简报速览 / 内参',
    departmentTags: ['comprehensive', 'international', 'operations'],
    audienceTags: ['director', 'executive', 'operations'],
    moduleBlueprint: ['刊头 ticker', '主头条', '双列内容', '数据边栏', '签发信息'],
  },
  {
    id: 'template-06',
    renderer: 'journal',
    name: '学术期刊版',
    title: '学术期刊周报',
    description: '强调摘要、正文分栏和归档感，适合长文本汇报。',
    accent: '#8B1A1A',
    chip: 'JOURNAL/06',
    focus: '适合严谨、长文本、可存档的研究或管理周报。',
    bestFor: '归档材料 / 学术管理',
    departmentTags: ['research', 'teaching', 'comprehensive'],
    audienceTags: ['director', 'executive', 'risk'],
    moduleBlueprint: ['刊头', '摘要', 'KPI 表', '双栏正文', '表格与脚注'],
  },
  {
    id: 'template-08',
    renderer: 'split-magazine',
    name: '分屏杂志版',
    title: '分屏杂志周报',
    description: '左侧导航与 KPI，右侧长内容和数据看板。',
    accent: '#7BAE7F',
    chip: 'SPLIT/08',
    focus: '适合信息密度较高的综合型周报。',
    bestFor: '综合周报 / 管理例会',
    departmentTags: ['comprehensive', 'operations', 'research', 'teaching'],
    audienceTags: ['director', 'executive', 'operations'],
    moduleBlueprint: ['侧栏 KPI', '要览总览', '分类工作流', '数据看板', '签发信息'],
  },
  {
    id: 'template-09',
    renderer: 'swiss-grid',
    name: '瑞士版式',
    title: '瑞士网格周报',
    description: '强调结构秩序和数字可读性，适合经营复盘。',
    accent: '#CC1A1A',
    chip: 'SWISS/09',
    focus: '适合追求严谨层级和数字表达的管理周报。',
    bestFor: '经营复盘 / 数据汇报',
    departmentTags: ['comprehensive', 'operations', 'research', 'strategy'],
    audienceTags: ['director', 'executive', 'risk'],
    moduleBlueprint: ['刊头与 ticker', 'KPI 条带', '要览与进展网格', '指标与答辩表', '签发信息'],
  },
  {
    id: 'template-11',
    renderer: 'neo-brutal-poster',
    name: '野兽战情版',
    title: '新野兽派战情周报',
    description: '强调海报式头版、高对比色块与任务战情分区，适合阶段冲刺复盘。',
    accent: '#FF5A2F',
    chip: 'BRUTAL/11',
    focus: '适合冲刺阶段、战役执行与跨团队协同周报。',
    bestFor: '战情复盘 / 冲刺周会',
    departmentTags: ['operations', 'strategy', 'comprehensive', 'industry'],
    audienceTags: ['executive', 'operations', 'director'],
    moduleBlueprint: ['宣言头版', '核心战绩', '三轨任务', '时间轴', '签发信息'],
  },
]
