export const fallbackSections = [
  {
    title: '自动结构化结果',
    description: '当前文档还没有抽取出完整章节，系统展示默认结构。',
    items: [
      { title: '上传原文', body: '请在左侧上传 PDF/Word/TXT 或直接粘贴文本。', tag: '输入' },
      { title: '点击转换', body: '系统会先结构化整理，再生成可预览 HTML。', tag: '流程' },
    ],
  },
]

export const templateCatalog = [
  {
    id: 'template-01',
    renderer: 'minimal',
    name: '极简版',
    title: '极简周报版式',
    description: '基于原始极简 HTML 拆分，突出大标题、表格进展和数据墙。',
    accent: '#121212',
    chip: 'MINIMAL/01',
    focus: '适合正式汇报、快速浏览和打印归档。',
    bestFor: '管理层简报',
    departmentTags: ['comprehensive', 'operations', 'research', 'teaching'],
    audienceTags: ['director', 'executive', 'operations'],
    moduleBlueprint: ['封面摘要', '重点要览', '四象限工作', '数据看板', '签发信息'],
  },
  {
    id: 'template-02',
    renderer: 'magazine',
    name: '杂志版',
    title: '杂志封面周报',
    description: '保留原杂志感封面、目录、专题导读和图表区。',
    accent: '#C8382A',
    chip: 'MAGAZINE/02',
    focus: '适合品牌感较强的汇报场景和对外展示式周报。',
    bestFor: '专题汇报 / 品牌展示',
    departmentTags: ['comprehensive', 'international', 'research'],
    audienceTags: ['director', 'executive'],
    moduleBlueprint: ['封面主稿', '要览导读', '分栏工作', '数据图表', '签发信息'],
  },
  {
    id: 'template-03',
    renderer: 'ink',
    name: '国风版',
    title: '国风卷轴周报',
    description: '完整保留宣纸、水墨、卷轴、章回式结构和进度卷轴。',
    accent: '#C41E3A',
    chip: 'INK/03',
    focus: '适合高辨识度展示，强调仪式感与章节叙事。',
    bestFor: '特色汇报 / 对外展示',
    departmentTags: ['comprehensive', 'international', 'teaching'],
    audienceTags: ['director', 'executive'],
    moduleBlueprint: ['封面信息', '卷轴要览', '四类重点工作', '数据板块', '签发信息'],
  },
  {
    id: 'template-04',
    renderer: 'dashboard-plus',
    name: '仪表盘版',
    title: '控制台仪表盘周报',
    description: '保留深色驾驶舱、时间线、看板、数值墙和侧边导航。',
    accent: '#00E5FF',
    chip: 'DASHBOARD/04',
    focus: '适合执行追踪、项目例会和高频运营复盘。',
    bestFor: '运营周会 / 项目推进',
    departmentTags: ['operations', 'research', 'comprehensive'],
    audienceTags: ['operations', 'executive'],
    moduleBlueprint: ['头部 KPI', '时间线要览', '分类看板', '数据可视化', '签发信息'],
  },
  {
    id: 'template-05',
    renderer: 'news',
    name: '新闻简报版',
    title: '新闻简报周报',
    description: '保留新闻刊头、ticker、三栏正文和右侧数据面板。',
    accent: '#F5C842',
    chip: 'NEWS/05',
    focus: '适合信息密度高、亮点多的简报型周报。',
    bestFor: '简报速览 / 内参',
    departmentTags: ['comprehensive', 'international', 'operations'],
    audienceTags: ['director', 'executive', 'operations'],
    moduleBlueprint: ['刊头 ticker', '主头条', '双列故事流', '数据边栏', '签发信息'],
  },
  {
    id: 'template-06',
    renderer: 'journal',
    name: '学术期刊版',
    title: '学术期刊周报',
    description: '保留论文期刊排版、摘要、双栏正文、表格和脚注信息。',
    accent: '#8B1A1A',
    chip: 'JOURNAL/06',
    focus: '适合严肃、长文本、可存档的研究或管理周报。',
    bestFor: '归档材料 / 学术管理',
    departmentTags: ['research', 'teaching', 'comprehensive'],
    audienceTags: ['director', 'executive', 'risk'],
    moduleBlueprint: ['刊头', '摘要', 'KPI 行', '双栏正文', '表格与脚注'],
  },
  {
    id: 'template-07',
    renderer: 'cyber',
    name: '赛博版',
    title: '赛博控制台周报',
    description: '保留矩阵雨、霓虹 HUD、矩阵卡片和终端式元信息。',
    accent: '#00FFFF',
    chip: 'CYBER/07',
    focus: '适合技术、创新、AI 项目类汇报，视觉冲击强。',
    bestFor: '技术周报 / 创新项目',
    departmentTags: ['research', 'operations', 'international'],
    audienceTags: ['executive', 'operations', 'director'],
    moduleBlueprint: ['系统封面', 'HUD 要览', '矩阵工作流', '数据终端', '元信息终端'],
  },
]
